### ISSUE TITLE
Can not build on Mac

### ISSUE THREAD

**Issue by zxhfirefox** [openglsuperbible/sb7code#22]
can not build on Mac OS 10.11.
`
/sb7code/include/GL/glext.h:6165:22: error: typedef redefinition with
      different types ('unsigned int' vs 'void *')
typedef unsigned int GLhandleARB;
                     ^
/System/Library/Frameworks/OpenGL.framework/Headers/gltypes.h:28:18: note: previous definition is here
typedef void    *GLhandleARB;
                 ^
1 warning and 1 error generated.
`

**Comment by Plimsky** [comment]
Hellow @zxhfirefox ! Did you find a solution for this problem ? I've got the same too 😢

**Comment by zxhfirefox** [comment]
@Plimsky , I fixed it by googling the problem, but I don't remember how did I fix it, really sorry.
